# Generated by Django 4.2.17 on 2025-01-23 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Usuario_django", "0002_tipo_usuario_usuario_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("resumo", models.TextField(blank=True, null=True)),
                ("arquivo", models.FileField(upload_to="")),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_modificacao", models.DateTimeField(auto_now=True)),
                (
                    "proprietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_proprietario",
                        to="Usuario_django.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PermissaoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_concessao", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_concedente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissoes_concedidas",
                        to="Usuario_django.usuario",
                    ),
                ),
                (
                    "usuario_permitido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissoes_recebidas",
                        to="Usuario_django.usuario",
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario_concedente", "usuario_permitido")},
            },
        ),
    ]
