# Generated by Django 4.2.17 on 2025-01-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Documentos", "0002_documento_data_documento_alter_documento_arquivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="secreto",
            field=models.BooleanField(default=False),
        ),
    ]
