# Generated by Django 4.2.17 on 2025-01-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Documentos", "0003_documento_secreto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="arquivo",
            field=models.FileField(blank=True, null=True, upload_to="protected/"),
        ),
        migrations.AlterField(
            model_name="documento",
            name="data_documento",
            field=models.DateField(),
        ),
    ]
