# Generated by Django 4.2.17 on 2025-01-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Documentos", "0004_alter_documento_arquivo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="data_documento",
            field=models.DateTimeField(),
        ),
    ]
