# Generated by Django 4.2.17 on 2025-01-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Documentos", "0006_alter_documento_data_documento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="data_documento",
            field=models.DateTimeField(),
        ),
    ]
