# Generated by Django 4.2.17 on 2025-02-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Documentos", "0007_alter_documento_data_documento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tipo_documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.TextField(default=None, max_length=255)),
            ],
        ),
    ]
