# Generated by Django 4.2.17 on 2025-02-16 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Documentos", "0008_tipo_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Documentos.tipo_documento",
            ),
            preserve_default=False,
        ),
    ]
