# Generated by Django 4.2.17 on 2025-01-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuario_django", "0002_tipo_usuario_usuario_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
