# Generated by Django 4.2.17 on 2025-01-27 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Usuario_django", "0004_remove_usuario_detalhes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Usuario_django.tipo_usuario",
                unique=True,
            ),
        ),
    ]
