# Generated by Django 4.2.17 on 2025-01-27 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Usuario_django", "0005_alter_usuario_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Usuario_django.tipo_usuario",
            ),
        ),
    ]
